config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "home/index"
  resources :reports
  resources :components
  resources :computers
  resources :laboratories
  resources :professors

  namespace :api do
    namespace :v1 do
      resources :reports, only: [:index, :create, :show, :update]
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/computer.rb
class Computer < ApplicationRecord
  belongs_to :laboratory
  has_many :components, dependent: :destroy
  has_many :reports, dependent: :destroy

  validates :serial_num, presence: true, uniqueness: true
end

app/controllers/computers_controller.rb
class ComputersController < ApplicationController
  before_action :set_computer, only: %i[ show edit update destroy ]

  # GET /computers or /computers.json
  def index
    @computers = Computer.all
  end

  # GET /computers/1 or /computers/1.json
  def show
  end

  # GET /computers/new
  def new
    @computer = Computer.new
  end

  # GET /computers/1/edit
  def edit
  end

  # POST /computers or /computers.json
  def create
    @computer = Computer.new(computer_params)

    respond_to do |format|
      if @computer.save
        format.html { redirect_to @computer, notice: "Computer was successfully created." }
        format.json { render :show, status: :created, location: @computer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /computers/1 or /computers/1.json
  def update
    respond_to do |format|
      if @computer.update(computer_params)
        format.html { redirect_to @computer, notice: "Computer was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @computer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /computers/1 or /computers/1.json
  def destroy
    @computer.destroy!

    respond_to do |format|
      format.html { redirect_to computers_path, notice: "Computer was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_computer
      @computer = Computer.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def computer_params
      params.expect(computer: [ :serial_num, :status, :brand, :team_num, :laboratory_id ])
    end
end

app/helpers/computers_helper.rb
module ComputersHelper
end

app/views/computers/_computer.html.erb
<div id="<%= dom_id computer %>">
  <div>
    <strong>Serial num:</strong>
    <%= computer.serial_num %>
  </div>

  <div>
    <strong>Status:</strong>
    <%= computer.status %>
  </div>

  <div>
    <strong>Brand:</strong>
    <%= computer.brand %>
  </div>

  <div>
    <strong>Team num:</strong>
    <%= computer.team_num %>
  </div>

  <div>
    <strong>Laboratory:</strong>
    <%= computer.laboratory_id %>
  </div>

</div>

app/views/computers/_form.html.erb
<%= form_with(model: computer) do |form| %>
  <% if computer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(computer.errors.count, "error") %> prohibited this computer from being saved:</h2>

      <ul>
        <% computer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :serial_num, style: "display: block" %>
    <%= form.text_field :serial_num %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :brand, style: "display: block" %>
    <%= form.text_field :brand %>
  </div>

  <div>
    <%= form.label :team_num, style: "display: block" %>
    <%= form.number_field :team_num %>
  </div>

  <div>
    <%= form.label :laboratory_id, style: "display: block" %>
    <%= form.text_field :laboratory_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/computers/edit.html.erb
<% content_for :title, "Editing computer" %>

<h1>Editing computer</h1>

<%= render "form", computer: @computer %>

<br>

<div>
  <%= link_to "Show this computer", @computer %> |
  <%= link_to "Back to computers", computers_path %>
</div>

app/views/computers/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Computers" %>

<h1>Computers</h1>

<div id="computers">
  <% @computers.each do |computer| %>
    <%= render computer %>
    <p>
      <%= link_to "Show this computer", computer %>
    </p>
  <% end %>
</div>

<%= link_to "New computer", new_computer_path %>

app/views/computers/new.html.erb
<% content_for :title, "New computer" %>

<h1>New computer</h1>

<%= render "form", computer: @computer %>

<br>

<div>
  <%= link_to "Back to computers", computers_path %>
</div>

app/views/computers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @computer %>

<div>
  <%= link_to "Edit this computer", edit_computer_path(@computer) %> |
  <%= link_to "Back to computers", computers_path %>

  <%= button_to "Destroy this computer", @computer, method: :delete %>
</div>