config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "home/index"
  resources :reports
  resources :components
  resources :computers
  resources :laboratories
  resources :professors

  namespace :api do
    namespace :v1 do
      resources :reports, only: [:index, :create, :show, :update]
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/laboratory.rb
class Laboratory < ApplicationRecord
  has_many :computers, dependent: :destroy
  has_many :reports, dependent: :destroy

  validates :name, :location, presence: true
end

app/controllers/laboratories_controller.rb
class LaboratoriesController < ApplicationController
  before_action :set_laboratory, only: %i[ show edit update destroy ]

  # GET /laboratories or /laboratories.json
  def index
    @laboratories = Laboratory.all
  end

  # GET /laboratories/1 or /laboratories/1.json
  def show
  end

  # GET /laboratories/new
  def new
    @laboratory = Laboratory.new
  end

  # GET /laboratories/1/edit
  def edit
  end

  # POST /laboratories or /laboratories.json
  def create
    @laboratory = Laboratory.new(laboratory_params)

    respond_to do |format|
      if @laboratory.save
        format.html { redirect_to @laboratory, notice: "Laboratory was successfully created." }
        format.json { render :show, status: :created, location: @laboratory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @laboratory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /laboratories/1 or /laboratories/1.json
  def update
    respond_to do |format|
      if @laboratory.update(laboratory_params)
        format.html { redirect_to @laboratory, notice: "Laboratory was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @laboratory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @laboratory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /laboratories/1 or /laboratories/1.json
  def destroy
    @laboratory.destroy!

    respond_to do |format|
      format.html { redirect_to laboratories_path, notice: "Laboratory was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_laboratory
      @laboratory = Laboratory.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def laboratory_params
      params.expect(laboratory: [ :lab_code, :name, :capacity, :location ])
    end
end

app/helpers/laboratories_helper.rb
module LaboratoriesHelper
end

app/views/laboratories/_form.html.erb
<%= form_with(model: laboratory) do |form| %>
  <% if laboratory.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(laboratory.errors.count, "error") %> prohibited this laboratory from being saved:</h2>

      <ul>
        <% laboratory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :lab_code, style: "display: block" %>
    <%= form.text_field :lab_code %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :capacity, style: "display: block" %>
    <%= form.number_field :capacity %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/laboratories/_laboratory.html.erb
<div id="<%= dom_id laboratory %>">
  <div>
    <strong>Lab code:</strong>
    <%= laboratory.lab_code %>
  </div>

  <div>
    <strong>Name:</strong>
    <%= laboratory.name %>
  </div>

  <div>
    <strong>Capacity:</strong>
    <%= laboratory.capacity %>
  </div>

  <div>
    <strong>Location:</strong>
    <%= laboratory.location %>
  </div>

</div>

app/views/laboratories/edit.html.erb
<% content_for :title, "Editing laboratory" %>

<h1>Editing laboratory</h1>

<%= render "form", laboratory: @laboratory %>

<br>

<div>
  <%= link_to "Show this laboratory", @laboratory %> |
  <%= link_to "Back to laboratories", laboratories_path %>
</div>

app/views/laboratories/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Laboratories" %>

<h1>Laboratories</h1>

<div id="laboratories">
  <% @laboratories.each do |laboratory| %>
    <%= render laboratory %>
    <p>
      <%= link_to "Show this laboratory", laboratory %>
    </p>
  <% end %>
</div>

<%= link_to "New laboratory", new_laboratory_path %>

app/views/laboratories/new.html.erb
<% content_for :title, "New laboratory" %>

<h1>New laboratory</h1>

<%= render "form", laboratory: @laboratory %>

<br>

<div>
  <%= link_to "Back to laboratories", laboratories_path %>
</div>

app/views/laboratories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @laboratory %>

<div>
  <%= link_to "Edit this laboratory", edit_laboratory_path(@laboratory) %> |
  <%= link_to "Back to laboratories", laboratories_path %>

  <%= button_to "Destroy this laboratory", @laboratory, method: :delete %>
</div>