config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "home/index"
  resources :reports
  resources :components
  resources :computers
  resources :laboratories
  resources :professors

  namespace :api do
    namespace :v1 do
      resources :reports, only: [:index, :create, :show, :update]
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/professor.rb
class Professor < ApplicationRecord
  has_many :reports, dependent: :destroy

  validates :name, :email, presence: true
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: %i[ show edit update destroy ]

  # GET /professors or /professors.json
  def index
    @professors = Professor.all
  end

  # GET /professors/1 or /professors/1.json
  def show
  end

  # GET /professors/new
  def new
    @professor = Professor.new
  end

  # GET /professors/1/edit
  def edit
  end

  # POST /professors or /professors.json
  def create
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: "Professor was successfully created." }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professors/1 or /professors/1.json
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to @professor, notice: "Professor was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1 or /professors/1.json
  def destroy
    @professor.destroy!

    respond_to do |format|
      format.html { redirect_to professors_path, notice: "Professor was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def professor_params
      params.expect(professor: [ :professor_code, :name, :email, :program, :phone ])
    end
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/_form.html.erb
<%= form_with(model: professor) do |form| %>
  <% if professor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
        <% professor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :professor_code, style: "display: block" %>
    <%= form.text_field :professor_code %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :program, style: "display: block" %>
    <%= form.text_field :program %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/professors/_professor.html.erb
<div id="<%= dom_id professor %>">
  <div>
    <strong>Professor code:</strong>
    <%= professor.professor_code %>
  </div>

  <div>
    <strong>Name:</strong>
    <%= professor.name %>
  </div>

  <div>
    <strong>Email:</strong>
    <%= professor.email %>
  </div>

  <div>
    <strong>Program:</strong>
    <%= professor.program %>
  </div>

  <div>
    <strong>Phone:</strong>
    <%= professor.phone %>
  </div>

</div>

app/views/professors/edit.html.erb
<% content_for :title, "Editing professor" %>

<h1>Editing professor</h1>

<%= render "form", professor: @professor %>

<br>

<div>
  <%= link_to "Show this professor", @professor %> |
  <%= link_to "Back to professors", professors_path %>
</div>

app/views/professors/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Professors" %>

<h1>Professors</h1>

<div id="professors">
  <% @professors.each do |professor| %>
    <%= render professor %>
    <p>
      <%= link_to "Show this professor", professor %>
    </p>
  <% end %>
</div>

<%= link_to "New professor", new_professor_path %>

app/views/professors/new.html.erb
<% content_for :title, "New professor" %>

<h1>New professor</h1>

<%= render "form", professor: @professor %>

<br>

<div>
  <%= link_to "Back to professors", professors_path %>
</div>

app/views/professors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @professor %>

<div>
  <%= link_to "Edit this professor", edit_professor_path(@professor) %> |
  <%= link_to "Back to professors", professors_path %>

  <%= button_to "Destroy this professor", @professor, method: :delete %>
</div>